<a href="https://colab.research.google.com/github/Katherine-bq/Google/blob/master/python%E7%9F%A5%E8%AF%86%E7%82%B9%E5%A4%8D%E4%B9%A0%E4%B9%8Bnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1.创建数组的三种方式
1.按步就班的 np.array() 用在列表和元组上 

2.定隔定点的 np.arange() 和 np.linspace()

3.一步登天的 np.ones(), np.zeros(), np.eye() 和 np.random.random()


In [0]:
import numpy as np

In [18]:
#np.array()
l = [3.5, 5, 2, 8, 4.2]
np.array(l)

array([3.5, 5. , 2. , 8. , 4.2])

- 定隔的arange:固定元素大小间隔
- 定点的 linspace：固定元素个数

函数 arange 的参数为起点 , 终点 , 间隔
    
    arange(start , stop , step)

其中 stop 必须要有，start 和 step 没有的话默认为 1。对着这个规则看看上面各种情况的输出。


In [19]:
print( np.arange(8) )
print( np.arange(2,8) )
print( np.arange(2,8,2))

[0 1 2 3 4 5 6 7]
[2 3 4 5 6 7]
[2 4 6]


函数 linspace 的参数为起点 , 终点 , 点数

    linspace (start , stop , num)

其中 start 和 stop 必须要有，num 没有的话默认为 50。对着这个规则看看上面各种情况的输出。


In [20]:
print(np.linspace(2,5))
print(np.linspace(2,6,3))
print(np.linspace(3,8,11))

[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]
[2. 4. 6.]
[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8. ]


- 用 zeros() 创建全是 0 的 n 维数组
- 用 ones() 创建全是 1 的 n 维数组
- 用 random() 创建随机 n 维数组
- 用 eye() 创建对角矩阵 (二维数组)

In [21]:

print( np.zeros(5) ) # 标量5代表形状(5,)
print( np.ones((2,3)) )
print( np.random.random((2,3,4)) )
print(np.eye(4))

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0.65434416 0.46955241 0.12291266 0.91554042]
  [0.40846581 0.74683114 0.82582914 0.72377314]
  [0.48169354 0.19668734 0.74486418 0.71416013]]

 [[0.66587912 0.47973087 0.31708785 0.74885573]
  [0.47395965 0.16009383 0.34156511 0.47250643]
  [0.8755907  0.96491471 0.21238332 0.771911  ]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]




#### 2.切片和数组
- 切片写法是 arr[start:stop:stop]
- 索引写法是 arr[index]

切片得到的是原数组的一个视图 (view) ，修改切片中的内容会改变原数组

索引得到的是原数组的一个复制 (copy)，修改索引中的内容不会改变原数组



In [22]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#索引：不会改变原有值
a = arr[6]
a = 12
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#切片:修改切片中内容会改变原数组
b = arr[2:5]
b[1] = 1111
arr

array([   0,    1,    2, 1111,    4,    5,    6,    7,    8,    9])

##### 2.1 布尔索引
就是用一个由布尔 (boolean) 类型值组成的数组来选择元素的方法。

In [0]:
code = np.array(['BABA', 'FB', 'JD', 'BABA', 'JD', 'FB'])
price = np.array([[170,177,169],[150,159,153],
                  [24,27,26],[165,170,167],
                  [22,23,20],[155,116,157]])

In [26]:
code == 'BABA' #返回布尔值
price[code == 'BABA']

array([[170, 177, 169],
       [165, 170, 167]])

In [27]:
price[ (code == 'FB')|(code == 'JD')]

array([[150, 159, 153],
       [ 24,  27,  26],
       [ 22,  23,  20],
       [155, 116, 157]])

#### 3.数组的变形
1.重塑 (reshape) 和打平 (ravel, flatten)

2.合并 (concatenate, stack) 和分裂 (split)

3.重复 (repeat) 和拼接 (tile)

4.其他操作 (sort, insert, delete, copy)


重塑 (reshape) 和打平 (ravel, flatten) 这两个操作仅仅只改变数组的维度

- 重塑是从低维到高维
- 打平是从高维到低维

##### 3.1 重塑和打平
函数 ravel() 或 flatten() 的不同之处是：

> ravel() 按「行主序」打平时没有复制原数组，按「列主序」在打平时复制了原数组；


> flatten() 在打平时复制了原数组。

In [28]:
arr1 = np.arange(12)
print(arr1)
print(arr1.reshape(4,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [29]:
ravel_arr = arr1.ravel()
ravel_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
flatten_arr = arr1.flatten()
flatten_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##### 3.2 合并
- 有通用的 concatenate
- 有专门的 vstack, hstack, dstack
- 有极简的 r_, c_

In [33]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


print(np.concatenate([arr1, arr2], axis=0))
print(np.concatenate([arr1, arr2], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


- vstack：v 代表 vertical，竖直合并，等价于 concatenate(axis=0)
- hstack：h 代表 horizontal，水平合并，等价于 concatenate(axis=1)
- dstack：d 代表 depth-wise，按深度合并，深度有点像彩色照片的 RGB 通道

In [34]:
print( np.vstack((arr1, arr2)) )
print( np.hstack((arr1, arr2)) )
print( np.dstack((arr1, arr2)) )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


##### 3.3 分裂
1.有通用的 split

2.有专门的 hsplit, vsplit

In [35]:
arr = np.arange(25).reshape((5,5))
first, second, third = np.split(arr,[1,3])
print( 'The first split is', first )
print( 'The second split is', second )
print( 'The third split is', third )

The first split is [[0 1 2 3 4]]
The second split is [[ 5  6  7  8  9]
 [10 11 12 13 14]]
The third split is [[15 16 17 18 19]
 [20 21 22 23 24]]


##### 3.4 重复和拼接

重复 (repeat) 和拼接 (tile) 这两个操作本质都是复制

- 重复是在元素层面复制
- 拼接是在数组层面复制